### PR TITLE
Request compression

### PR DESCRIPTION
**Pull request by treythomas123**
https://github.com/h2non/gock/issues/11

Only included gzip for now but it should be easy to add other compression types

### CODE REVIEW

**Comment by treythomas123** [comment]
Looks like the checks are failing because the example code uses gock imported from `"gopkg.in/h2non/gock.v1"` instead of using the files actually in this repo. It passes if I change the import for the failing example/test to point at my local clone that includes the changes.

**Comment by treythomas123** [comment]
Not sure how to fix this -- seems like maybe the travis config should copy the contents of the repo into `$GOPATH/gopkg.in/h2non/gock.v1` instead of `go get`ing it.

**Comment by h2non** [comment]
Yeah, I realized that. No worries for that.

**Comment by h2non** [comment]
Will fix that now. Thanks for the PR!

**Comment by treythomas123** [comment]
Cool, thanks for merging!

**Pull request merged**
